### ISSUE TITLE
No such file or directory: 'data/t2m_mean.npy'

### ISSUE THREAD

**Issue by fyyakaxyy** [h-y1heng/StableMoFusion#3]
Thanks for your great project, when I evaluate, the error is:

`
Loading gt_eval mode HumanML3D dataset ...
data/t2m_std.npy
Traceback (most recent call last):
  File "stablemofusion/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "stablemofusion/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "t2m/StableMoFusion/utils/scripts/evaluation.py", line 33, in <module>
    gt_loader = get_dataset_loader(opt, opt.batch_size, mode='gt_eval',split='test')
  File "t2m/StableMoFusion/motion_loader/dataset_motion_loaders.py", line 9, in get_dataset_loader
    dataset = get_dataset(opt, split, mode, accelerator)
  File "t2m/StableMoFusion/datasets/__init__.py", line 10, in get_dataset
    dataset = HumanML3D(opt, split, mode, accelerator)
  File "t2m/StableMoFusion/datasets/t2m_dataset.py", line 233, in __init__
    super(HumanML3D, self).__init__(opt, split, mode, accelerator)
  File "t2m/StableMoFusion/datasets/t2m_dataset.py", line 33, in __init__
    mean = np.load(pjoin(opt.eval_meta_dir, f'{opt.dataset_name}_mean.npy'))
  File "stablemofusion/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/t2m_mean.npy'
`

Does t2m_mean.npy is Mean.npy in HumanML3D?

**Comment by h-y1heng** [comment]
Sorry for not specifying it, we've updated the ./data/ in the repository. The `*_mean.npy` and `*_std.npy` files, are stats used for evaluation only, according to [text-to-motion](https://github.com/EricGuo5513/text-to-motion).

**Comment by fyyakaxyy** [comment]
> Sorry for not specifying it, we've updated the ./data/ in the repository. The `*_mean.npy` and `*_std.npy` files, are stats used for evaluation only, according to [text-to-motion](https://github.com/EricGuo5513/text-to-motion).

thanks
